apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rh-trex
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rh-trex
    app.kubernetes.io/part-of: rh-trex
  name: rh-trex
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: rh-trex
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: rh-trex
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/gallen-tenant/rh-trex/rh-trex@sha256:563d8d2cb1251990a752aef24e6359ceb4e7876a59ae1ce9790c4df9faf46e07
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
