apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rh-trex
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rh-trex
    app.kubernetes.io/part-of: rh-trex
  name: rh-trex
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app.kubernetes.io/instance: rh-trex
status:
  loadBalancer: {}
