apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rh-trex
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rh-trex
    app.kubernetes.io/part-of: rh-trex
  name: rh-trexcpu4
spec:
  port:
    targetPort: 8000
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: rh-trex
    weight: 100
status: {}
